name: Lint
on:
  push:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # no lint check for legacy
      - run: rm ./README.legacy.md
      - run: npx awesome-lint
